name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25.0.0

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Lint code (optional if you have ESLint)
      - name: Run Linter
        run: |
          if [ -f package.json ]; then
            npm run lint || echo "No lint script found, skipping linting."
          fi

      # Step 5: Run tests (Jest)
      - name: Run Tests
        run: |
          if [ -f package.json ]; then
            npm test || echo "No test script found, skipping tests."
          fi

      # Step 6: Build project (Parcel)
      - name: Build Project
        run: |
          if [ -f package.json ]; then
            npm run build || echo "No build script found, skipping build."
          fi
