name: Code Review

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        id: codeql

      - name: Save CodeQL Summary
        run: |
          echo "## CodeQL Scan Complete" > codeql-result.txt
          echo "${{ steps.codeql.outcome }}" >> codeql-result.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeql-result
          path: codeql-result.txt

  sonarcloud:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0

        env:
             SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
             SONAR_HOST_URL: https://sonarcloud.io
             SONAR_PROJECTKEY: ${{ secrets.SONAR_PROJECT_KEY }}
             SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
             
      - name: Save SonarCloud Summary
        run: |
          echo "## SonarCloud Scan Triggered" > sonarcloud-result.txt
          echo "See the SonarCloud dashboard for full results." >> sonarcloud-result.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sonarcloud-result
          path: sonarcloud-result.txt

  post-results:
    needs: [codeql, sonarcloud]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: codeql-result
          path: ./
      - uses: actions/download-artifact@v5
        with:
          name: sonarcloud-result
          path: ./
      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v3
        with:
          filePath: ./codeql-result.txt
          filePathInput2: ./sonarcloud-result.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
