name: Code Review

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        id: codeql

      - name: Save CodeQL Summary
        run: |
          echo "## CodeQL Scan Complete" > codeql-result.txt
          echo "${{ steps.codeql.outcome }}" >> codeql-result.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeql-result
          path: codeql-result.txt

  sonarcloud:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: Save SonarCloud Summary
        run: |
          echo "## SonarCloud Scan Triggered" > sonarcloud-result.txt
          echo "See the SonarCloud dashboard for full results." >> sonarcloud-result.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sonarcloud-result
          path: sonarcloud-result.txt

  post-results:
    needs: [codeql, sonarcloud]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v5
        with:
          name: codeql-result
          path: ./

      - uses: actions/download-artifact@v5
        with:
          name: sonarcloud-result
          path: ./

      - name: Combine results
        run: |
          echo "### 🧠 CodeQL & SonarCloud Summary" > final-result.txt
          echo "" >> final-result.txt
          cat codeql-result.txt >> final-result.txt
          echo "" >> final-result.txt
          cat sonarcloud-result.txt >> final-result.txt

      - name: Comment on Pull Request
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('final-result.txt', 'utf8');
            try {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body
              });
              console.log("Comment posted successfully ✅");
            } catch (error) {
              console.warn("⚠️ Could not post comment. Likely a forked PR or insufficient permissions.");
              console.warn(error.message);
            }
